### ISSUE TITLE
Error when starting the extension.

### ISSUE THREAD

**Issue by jrvgr** [dmfs/tempomate#74]
When i try to start the extension i get the following error: TypeError: issue is undefined

**Comment by dmfs** [comment]
hmm, are you sure your credentials are correct? Error handling is not very good yet and if the server responds with an authentication error, the extension will fail.

Please make sure that you pass an API token you generated in Jira, not your personal password.

Also, please note that Jira cloud is not supported yet, just in case you're trying that. Support is on the way. You might want to try the branch in #72 if that's the case.

**Comment by dmfs** [comment]
please also try out the latest version. It contains a large number of fixes and improvements.

**Comment by jrvgr** [comment]
I'm no longer a Jira user so this issue doesn't really apply to me anymore, so i'll close it.
